### ISSUE TITLE
DomainChangeMetadataEvent

### ISSUE THREAD

**Issue by vtolstov** [alexzorin/libvirt-go#42]
Hello. I need to listen for  events from libvirt about changing domain metadata. Does it possible to add this event?

**Comment by alexzorin** [comment]
Hi Vasily,

Do you mean metadata in the sense of [`virDomain[Get/Set]Metadata`](http://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetMetadata)?

I am not sure if libvirt emits events for changes there. But, if you can point out to me how this might be possible via the API: http://libvirt.org/html/libvirt-libvirt-domain.html#virDomainEventID , I'll gladly take a look.

**Comment by vtolstov** [comment]
Hmm... I miss that, thanks. I'm try to write to libvirt-devel and ask them.

**Comment by vtolstov** [comment]
I'm close this issue, because libvirt does not have this feature right now.
