### ISSUE TITLE
virDomainMigrate?

### ISSUE THREAD

**Issue by charliedrage** [alexzorin/libvirt-go#45]
Correct me if I'm blind, but has virDomainMigrate bindings been implemented?

**Comment by alexzorin** [comment]
No, you're right, it is not implemented.

**Comment by charliedrage** [comment]
Ah, thought so. Kind of new to Go, assumed it had an auto-import function similar to Ruby's C implementation / wrapper of ruby-libvirt.

Thanks :) I'll contribute to development.

**Comment by alexzorin** [comment]
To be fair, there are tools (swig, def2go), but I just didn't know about them at the time. Worth investigating.
