### ISSUE TITLE
some missed api function for storage vol

### ISSUE THREAD

**Issue by vtolstov** [alexzorin/libvirt-go#46]
@alexzorin can you add to this binding function 
https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolUpload
https://libvirt.org/html/libvirt-libvirt-storage.html#virStorageVolDownload 

thanks!

**Comment by vtolstov** [comment]
Thanks!

**Comment by alexzorin** [comment]
Np, See https://github.com/alexzorin/libvirt-go/blob/master/integration_test.go#L867-L962 for contrived example

Lemme know if problems

**Comment by vtolstov** [comment]
@alexzorin works fine.
