### ISSUE TITLE
add memoryStats and getVcpus

### ISSUE THREAD

**Issue by farss** [alexzorin/libvirt-go#52]
can you add memoryStats and getVcpus function
Thank you

**Comment by alexzorin** [comment]
I couldn't get memoryStats to work on lxc, but to be honest I don't think it is a code error but rather to do with the setup of lxc/cgroups in the test environment.

Check the branch out, let me know if it works for you.

I'm not keen on spending any real amount of time on this, so it'll be up to you if you it merged

**Comment by farss** [comment]
Thank you @alexzorin
It looks well on kvm/qemu

**Comment by farss** [comment]
It works!
